
try {
    
} catch (error) {
    
} finally{

}

// program to show try...catch in a program
const a= 100, b = 'a';

try {
    console.log(a/c);     
    console.log(a); 
}
catch(error) {
    // console.log('An error caught'); 
    console.log(error.message);  
} finally{
    console.log("I have the power of executing");
}

console.log("Don't underestimate yourself");

// const a= 100;
// const b = 'a';

// console.log(a/c);
       
// console.log(a);

